name: microshop
services:
  commercial_db:
    image: postgres:15.1-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microshop

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
